# Name of your site (displayed in the header)
name: André Carvalheira

# Short bio or description (displayed in the header)
bio: Product Manager

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# picture: assets/images/profile.png

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

#
# Flags below are optional
#
# analytics: UA-42257282-3
# disqus: hugoribeira
# twitter: mytwitter
 linkedin: in/acarvalheira
# github: eidge
 twitter: carvalheira1
rss: http://www.carvalheira.blog/feed.xml

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.carvalheira.blog

highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
  base_url: https://github.com

# Exclude these files from your production _site
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]
